### ISSUE TITLE
npm audit warning - path-to-regexp

### ISSUE THREAD

**Issue by apepper** [local-web-server/blacklist#2]
npm audit currently gives a warning for this package due to its dependencies.

Namely the `path-to-regexp` package creates this warning: https://github.com/advisories/GHSA-9wv6-86v2-598j

It is triggered because of the following dependency:

https://github.com/lwsjs/blacklist/blob/d553481c877fdfb5d3ac6d2d4d2e65249656262b/package.json#L20

If possible, please upgrade the package.

**Comment by 75lb** [comment]
See https://github.com/lwsjs/rewrite/issues/15
